# Generated by Django 4.2 on 2023-05-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranzas',
            fields=[
                ('Número_de_comprobante', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('Fecha_de_cobro', models.DateField(auto_now_add=True)),
                ('Cuánto_pagó', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cobranzas',
                'ordering': ['Número_de_comprobante'],
            },
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('Nombre', models.CharField(max_length=40)),
                ('DNI', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Teléfono', models.IntegerField()),
                ('E_mail', models.CharField(max_length=40)),
                ('Obra_Social_Prepaga', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'ordering': ['Nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('Número_de_orden', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Tratamiento_1', models.CharField(blank=True, max_length=100)),
                ('Tratamiento_2', models.CharField(blank=True, max_length=100)),
                ('Tratamiento_3', models.CharField(blank=True, max_length=100)),
                ('Monto', models.IntegerField()),
                ('Paciente_Dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Presupuestos', to='Cargas.pacientes')),
            ],
            options={
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['Número_de_orden'],
            },
        ),
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto', models.IntegerField()),
                ('Saldo', models.IntegerField()),
                ('Cuánto_pagó', models.IntegerField()),
                ('Número_de_comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cargas.presupuestos')),
                ('Número_de_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cargas.cobranzas')),
            ],
            options={
                'verbose_name_plural': 'Saldos',
                'ordering': ['Número_de_orden'],
            },
        ),
        migrations.AddField(
            model_name='cobranzas',
            name='Número_de_orden',
            field=models.ManyToManyField(auto_created=True, related_name='Cobranzas', to='Cargas.presupuestos'),
        ),
    ]
