# Generated by Django 4.2 on 2023-04-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('Nombre', models.CharField(max_length=40)),
                ('DNI', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('Teléfono', models.IntegerField()),
                ('E_mail', models.CharField(max_length=40)),
                ('Obra_Social_Prepaga', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('Número_de_orden', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Tratamiento_1', models.CharField(max_length=100)),
                ('Tratamiento_2', models.CharField(max_length=100)),
                ('Tratamiento_3', models.CharField(max_length=100)),
                ('Monto', models.IntegerField(max_length=10)),
                ('DNI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cargas.pacientes')),
            ],
        ),
    ]
