# Generated by Django 4.2 on 2023-05-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldos',
            name='Saldo',
            field=models.IntegerField(null=True),
        ),
    ]
