# Generated by Django 4.2 on 2023-04-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestos',
            old_name='DNI',
            new_name='Paciente',
        ),
    ]
