# Generated by Django 4.2 on 2023-04-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranzas',
            fields=[
                ('Número_de_comprobante', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('Número_de_orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Cargas.presupuestos')),
                ('Fecha_de_cobro', models.DateField(auto_now_add=True)),
                ('Cuánto_pagó', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cobranzas',
                'ordering': ['Número_de_comprobante'],
            },
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'ordering': ['Nombre'], 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='presupuestos',
            options={'ordering': ['Número_de_orden'], 'verbose_name_plural': 'Presupuestos'},
        ),
        migrations.RenameField(
            model_name='presupuestos',
            old_name='DNI',
            new_name='Paciente_Dni',
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='DNI',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Monto',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Número_de_orden',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Tratamiento_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Tratamiento_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Tratamiento_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
