# Generated by Django 4.2 on 2023-05-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0002_alter_saldos_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldos',
            name='Cuánto_pagó',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='saldos',
            name='Monto',
            field=models.IntegerField(null=True),
        ),
    ]
