# Generated by Django 4.2 on 2023-04-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0002_rename_dni_presupuestos_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestos',
            old_name='Paciente',
            new_name='Paciente_Dni',
        ),
    ]
