# Generated by Django 4.2 on 2023-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0002_cobranzas_alter_pacientes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranzas',
            name='Número_de_orden',
        ),
        migrations.AddField(
            model_name='cobranzas',
            name='Número_de_orden',
            field=models.ManyToManyField(to='Cargas.presupuestos'),
        ),
    ]
