# Generated by Django 4.2 on 2023-05-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0002_alter_tratamientos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientos',
            name='Código_interno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tratamientos',
            name='Tipo',
            field=models.CharField(max_length=50),
        ),
    ]
