# Generated by Django 4.2 on 2023-04-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0003_remove_cobranzas_número_de_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranzas',
            name='Número_de_orden',
            field=models.ManyToManyField(auto_created=True, to='Cargas.presupuestos'),
        ),
    ]
