# Generated by Django 4.2 on 2023-05-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0003_alter_saldos_cuánto_pagó_alter_saldos_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldos',
            name='Número_de_comprobante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cargas.presupuestos'),
        ),
        migrations.AlterField(
            model_name='saldos',
            name='Número_de_orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cargas.cobranzas'),
        ),
    ]
