# Generated by Django 4.2 on 2023-04-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0004_alter_cobranzas_número_de_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Número_de_orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cargas.presupuestos')),
            ],
        ),
    ]
