# Generated by Django 4.2 on 2023-06-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0004_alter_tratamientos_propios_código_interno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranzaspresupuestos_inter',
            options={'ordering': ['cobranzas'], 'verbose_name_plural': 'Cobranzas_presupuesto_intermedia'},
        ),
    ]
