# Generated by Django 4.2 on 2023-05-15 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0004_alter_saldos_número_de_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldos',
            name='Número_de_comprobante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cargas.cobranzas'),
        ),
        migrations.AlterField(
            model_name='saldos',
            name='Número_de_orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cargas.presupuestos'),
        ),
    ]
