# Generated by Django 4.2 on 2023-04-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0005_saldos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldos',
            name='id',
        ),
        migrations.AlterField(
            model_name='saldos',
            name='Número_de_orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Cargas.presupuestos'),
        ),
    ]
