# Generated by Django 4.2 on 2023-06-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0005_alter_cobranzaspresupuestos_inter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranzaspresupuestos_inter',
            options={},
        ),
    ]
