# Generated by Django 4.2 on 2023-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0006_remove_saldos_id_alter_saldos_número_de_orden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saldos',
        ),
    ]
