# Generated by Django 4.2 on 2023-06-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0006_alter_cobranzaspresupuestos_inter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestos',
            name='Tratamiento_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Tratamiento_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Tratamiento_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
