# Generated by Django 4.2 on 2023-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0007_delete_saldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranzas',
            name='Orden',
            field=models.IntegerField(default=0, verbose_name=models.ManyToManyField(auto_created=True, to='Cargas.presupuestos')),
        ),
    ]
