# Generated by Django 4.2 on 2023-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0008_cobranzas_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranzas',
            name='Número_de_orden',
        ),
        migrations.RemoveField(
            model_name='cobranzas',
            name='Orden',
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='Número_de_comprobante',
            field=models.ManyToManyField(to='Cargas.cobranzas'),
        ),
    ]
