# Generated by Django 4.2 on 2023-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0012_alter_cobranzas_número_de_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestos',
            name='Número_de_comprobante',
        ),
        migrations.AddField(
            model_name='cobranzas',
            name='Orden',
            field=models.IntegerField(default=0, verbose_name=models.ManyToManyField(auto_created=True, to='Cargas.presupuestos')),
        ),
        migrations.RemoveField(
            model_name='cobranzas',
            name='Número_de_orden',
        ),
        migrations.AddField(
            model_name='cobranzas',
            name='Número_de_orden',
            field=models.ManyToManyField(auto_created=True, to='Cargas.presupuestos'),
        ),
    ]
