# Generated by Django 4.2 on 2023-05-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0013_remove_presupuestos_número_de_comprobante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranzas',
            name='Orden',
        ),
        migrations.AddField(
            model_name='presupuestos',
            name='Número_de_comprobante',
            field=models.ManyToManyField(auto_created=True, to='Cargas.cobranzas'),
        ),
        migrations.RemoveField(
            model_name='cobranzas',
            name='Número_de_orden',
        ),
        migrations.AddField(
            model_name='cobranzas',
            name='Número_de_orden',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Cargas.presupuestos'),
        ),
    ]
