# Generated by Django 4.2 on 2023-05-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0016_rename_número_de_orden_cobranzas_número_de_orden_relación_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobranzas',
            old_name='Número_de_orden_relación',
            new_name='Número_de_orden',
        ),
    ]
