# Generated by Django 4.2 on 2023-05-11 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cargas', '0017_rename_número_de_orden_relación_cobranzas_número_de_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranzas',
            name='Número_de_orden',
            field=models.ManyToManyField(auto_created=True, related_name='Cobranzas', to='Cargas.presupuestos'),
        ),
        migrations.AlterField(
            model_name='presupuestos',
            name='Paciente_Dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Presupuestos', to='Cargas.pacientes'),
        ),
    ]
